apiVersion: v1
kind: Service
metadata:
  name: house-pricing-api-service
spec:
  selector:
    app: house-pricing-api  # Doit correspondre au label dans le Deployment
  ports:
    - protocol: TCP
      port: 8000          # Port exposé par le Service
      targetPort: 8000    # Port du conteneur
  type: LoadBalancer      # Pour exposer le Service à l'extérieur (en local, utilise NodePort)